<?php
/**
 * @file
 * This is the file description for Tagger Data Publisher module.
 *
 * In this more verbose, multi-line description, you can specify what this
 * file does exactly. Make sure to wrap your documentation in column 78 so
 * that the file can be displayed nicely in default-sized consoles.
 */

/**
 * Implements hook_menu().
 */
function tagger_data_publisher_menu() {
  $items = array();

  // Type '$item ⇥' to create a new menu item.

  return $items;
}
