<?php
/**
 * @file
 * This is the file description for Wiki Tag Admin module.
 *
 * In this more verbose, multi-line description, you can specify what this
 * file does exactly. Make sure to wrap your documentation in column 78 so
 * that the file can be displayed nicely in default-sized consoles.
 */

/**
 * Implements hook_menu().
 */
function wiki_tag_admin_menu() {
  $items = array();
  
  $items['admin/settings/wiki_tag_admin'] = array(
    'title' => 'Menu item',
    'description' => 'The description of the menu item. It is used as title attribute and on the administration overview page.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('wiki_tag_settings_form'),
    'access arguments' => array('administer wiki_tag_admin'),
  );

  
  
  $items['admin/wiki_tag_import'] = array(
    'title' => 'Menu item',
    'description' => 'The description of the menu item. It is used as title attribute and on the administration overview page.',
    'page callback' => 'wiki_tag_admin_page',
    'access arguments' => array('administer wiki_tag_admin'),
  );

  
  // Type '$item ⇥' to create a new menu item.

  return $items;
}

function wiki_tag_admin_page() {
  
  $output  = '';
  //$output .= print_r(variable_get('wiki_tag_admin_wikipowered_vocabularies', null),1). '<br />';
  //$output .= variable_get('wiki_tag_admin_wikipedia_uri', null);
  $opts = array(
   'http'=> array(
     'user_agent'=> $_SERVER['HTTP_USER_AGENT']
   )
  );

  $dd = stream_context_create($opts);
  $string = file_get_contents(variable_get('wiki_tag_admin_wikipedia_uri', null), null, $dd);
  $xml = simplexml_load_string($string);
  foreach ($xml->channel->item AS $item) {
    $output .= '<h3>'. $item->title .'</h3>';
    $output .= '<a href="'. $item->link .'">'. $item->link .'</a>';
    $output .= '<p>'. $item->description .'</p>';
  }
  
  return $output;
}

function wiki_tag_settings_form($form, &$form_state) {
  
  $vocabulary = taxonomy_get_vocabularies();
  $vocabularies = array(); /* Change to array('0' => '--none--'); if you want a none option*/
  foreach ($vocabulary as $item) {
    $key = $item->vid;
    $value = $item->name;
    $vocabularies[$key] = $value;
  }
  
  $form['wikipedia_uri'] = array(
    '#type' => 'textfield',
    '#title' => t('Wikipedia URI'),
    '#description' => t('Select the right URI (atom...)'),
    '#default_value' => variable_get('wiki_tag_admin_wikipedia_uri', null),

  );
  $form['wikipowered_vocabularies'] = array(
    '#type' => 'select',
    '#title' => t('Vocabularies'),
    '#multiple' => TRUE,
    '#description' => t('The description appears usually below the item.'),
    '#options' => $vocabularies,
    '#default_value' => variable_get('wiki_tag_admin_wikipowered_vocabularies', null),
  );
  
  $form['save'] = array(
    '#type' => 'submit',
    '#value' => t('Save'),
  );
  
  return $form;
}

function wiki_tag_settings_form_submit($form, &$form_state) {
  variable_set('wiki_tag_admin_wikipowered_vocabularies', $form_state['values']['wikipowered_vocabularies']);
  variable_set('wiki_tag_admin_wikipedia_uri', $form_state['values']['wikipedia_uri']);
}


/*

http://da.wikipedia.org/w/api.php?action=query&list=logevents&lelimit=500&letype=delete
http://da.wikipedia.org/w/api.php?action=query&list=recentchanges&rctype=new&rcnamespace=0&rclimit=500

*/